<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

  <!-- Shared assembly / package metadata -->
  <PropertyGroup>
    <Product>Celsius</Product>
    <Company>burakdmrbkr</Company>
    <Authors>burakdmrbkr</Authors>
    <Copyright>Copyright (c) 2026 burakdmrbkr</Copyright>
    <VersionPrefix>0.1.0</VersionPrefix>
    <VersionSuffix>beta</VersionSuffix>
    <RepositoryUrl>https://github.com/burakdmrbkr/Celsius</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/burakdmrbkr/Celsius</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

</Project>
